[Feat] Tag Modal 기능추가 (PanModal)
HGU-iOS-Study-Group/Pomodoro pull request #18
Opened 2023-11-16 17:27 UTC by singhae

2023-11-17 05:10 UTC, jeonyeohun requested changes
수고하셨습니다
- PanModal Pod 말고 기존 방식대로 추가해주세요
- 코드 정리 부탁드립니다.

2023-11-17 05:10 UTC, jeonyeohun commented on Sources/MainScene/TagModal/TagModalViewController.swift
> +    private let items = (0...10).map(String.init)
어떤 의도인지 잘 모르겠어요. 11개의 `""` 값이 있는 배열이 필요한 것이라면
`Array(repeating: "", count: 11)` 이게 더 이해하기 쉬울 것 같아요.

2023-11-17 05:10 UTC, jeonyeohun commented on Sources/MainScene/ViewControllers/MainViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1, execute: {
delay는 어떤 이유로 필요한 것인가요?

2023-11-17 05:10 UTC, jeonyeohun commented on Sources/MainScene/TagModal/TagModalViewController.swift
> +    private let tableView: UITableView = {
variable 사이에 공백 넣어주세요

2023-11-17 05:10 UTC, jeonyeohun commented on Sources/MainScene/TagModal/TagModalViewController.swift
> +        let view = UITableView()
Then 사용 부탁드립니다.

2023-11-17 05:10 UTC, jeonyeohun commented on Sources/MainScene/TagModal/TagModalViewController.swift
> +    var scrollView: UIScrollView {
요거 왜 필요한지 설명해주실 수 있을까요?

2023-11-17 05:10 UTC, jeonyeohun commented on Podfile
> +target 'Pomodoro' do
Pod 사용하지 마시고 Swift package manager 사용 부탁드립니다.

2023-11-17 05:10 UTC, jeonyeohun commented on Pods/PanModal/PanModal/View/DimmedView.swift
> +//  DimmedView.swift
서드파티 파일은 직접 프로젝트에 포함 안시키는게 좋습니다

2023-11-17 05:10 UTC, jeonyeohun commented on Sources/MainScene/ViewControllers/MainViewController.swift
> +import PanModal
직접 구현하기엔 어떤게 어려우셨어요?

2023-11-19 12:23 UTC, singhae commented on Sources/MainScene/TagModal/TagModalViewController.swift
> +    private let tableView: UITableView = {
여기서 공백이란 한 줄 띄우라는 말씀이시죠?

2023-11-20 11:17 UTC, jeonyeohun approved these changes

2023-11-20 11:17 UTC, merged